plot_DomData_Floors() = error("Extension not loaded")
plot_DomData_PMT() = error("Extension not loaded")
plot_DomData_Rings() = error("Extension not loaded")
plot_DomData_linFit_array() = error("Extension not loaded")
plot_DomData_linFit_ganz() = error("Extension not loaded")
plot_DomData_linFit_test2() = error("Extension not loaded")
plot_DomData_linFit_test1() = error("Extension not loaded")
plot_DomData_Event_test2() = error("Extension not loaded")
plot_DomData_Event_test1() = error("Extension not loaded")

