plot_DomDataV3_Floors() = error("Extension not loaded")
plot_DataV3_Event_alt() = error("Extension not loaded")
plot_DataV3_Events_alt() = error("Extension not loaded")
plot_DomDataV3_PMT() = error("Extension not loaded")
plot_DomDataV3_Rings() = error("Extension not loaded")
